import os
import json
import uuid
import asyncio
import os
import shutil
import logging
import traceback
from datetime import datetime, timezone

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import StreamingResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage

from agents import main_assistant_agent, AGENT_NAME
from all_sub_agents import SUB_AGENT_NAMES
from storage_paths import agent_dir

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("personal_assistant")

# ---------------------------------------------------------------------------
# Resolve paths relative to THIS file, not the process's current working
# directory (which may differ from the project root depending on how the
# platform/container launches uvicorn) — avoids "Directory does not exist"
# errors when mounting /static.
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")

# ---------------------------------------------------------------------------
# PERSISTENCE PATHS — everything (thread index + uploaded files) lives inside
# the persistent /agent storage bucket, under this agent's own folder, so a
# Space restart/redeploy never loses conversation history or attachments.
# ---------------------------------------------------------------------------
MAIN_MEMORY_DIR = agent_dir(AGENT_NAME)
THREADS_INDEX_PATH = os.path.join(MAIN_MEMORY_DIR, "threads.json")
UPLOADS_DIR = os.path.join(MAIN_MEMORY_DIR, "uploads")
UI_HISTORY_DIR = os.path.join(MAIN_MEMORY_DIR, "ui_history")
os.makedirs(UPLOADS_DIR, exist_ok=True)
os.makedirs(UI_HISTORY_DIR, exist_ok=True)

_threads_lock = asyncio.Lock()

app = FastAPI(title="Personal Assistant")
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


@app.exception_handler(Exception)
async def _log_unhandled_exceptions(request, exc):
    logger.error("Unhandled error on %s %s:\n%s", request.method, request.url.path, traceback.format_exc())
    return JSONResponse({"error": str(exc)}, status_code=500)


# ---------------------------------------------------------------------------
# THREAD INDEX HELPERS (so the sidebar / history survive a page refresh)
# ---------------------------------------------------------------------------
def _read_threads():
    if not os.path.exists(THREADS_INDEX_PATH):
        return []
    try:
        with open(THREADS_INDEX_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


def _write_threads(threads):
    with open(THREADS_INDEX_PATH, "w", encoding="utf-8") as f:
        json.dump(threads, f, ensure_ascii=False, indent=2)


def _ui_history_path(thread_id: str) -> str:
    # UUIDs are generated by this app; replacing path separators is an extra
    # guard because this value is also received from the browser.
    safe_id = str(thread_id).replace("/", "_").replace("\\\\", "_")
    return os.path.join(UI_HISTORY_DIR, f"{safe_id}.json")


def _read_ui_history(thread_id: str) -> list:
    path = _ui_history_path(thread_id)
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            value = json.load(f)
        return value if isinstance(value, list) else []
    except Exception:
        logger.warning("Could not read UI history for %s", thread_id)
        return []


def _write_ui_history(thread_id: str, turns: list):
    path = _ui_history_path(thread_id)
    temp_path = f"{path}.tmp"
    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(turns[-80:], f, ensure_ascii=False, indent=2)
    os.replace(temp_path, path)


def _append_ui_turn(thread_id: str, turn: dict):
    turns = _read_ui_history(thread_id)
    turns.append(turn)
    _write_ui_history(thread_id, turns)


def _replace_last_assistant_turn(thread_id: str, turn: dict):
    turns = _read_ui_history(thread_id)
    for index in range(len(turns) - 1, -1, -1):
        if turns[index].get("role") == "assistant":
            turns[index] = turn
            _write_ui_history(thread_id, turns)
            return
    turns.append(turn)
    _write_ui_history(thread_id, turns)


async def _touch_thread(thread_id: str, title: str | None = None):
    async with _threads_lock:
        threads = _read_threads()
        now = datetime.now(timezone.utc).isoformat()
        found = None
        for t in threads:
            if t["id"] == thread_id:
                found = t
                break
        if found is None:
            found = {
                "id": thread_id,
                "title": title or "নতুন কথোপকথন",
                "created_at": now,
                "updated_at": now,
            }
            threads.insert(0, found)
        else:
            found["updated_at"] = now
            if title and found.get("title") == "নতুন কথোপকথন":
                found["title"] = title
            threads.remove(found)
            threads.insert(0, found)
        _write_threads(threads)


# ---------------------------------------------------------------------------
# API: index page
# NOTE: methods include HEAD because HF Spaces' own health-check / proxy
# probes "/" with HEAD requests — a plain @app.get() route 405's those,
# which repeated in the logs and can make the platform think the
# container is unhealthy.
# ---------------------------------------------------------------------------
@app.api_route("/", methods=["GET", "HEAD"])
async def index():
    from fastapi.responses import FileResponse
    return FileResponse(os.path.join(STATIC_DIR, "index.html"))


# ---------------------------------------------------------------------------
# API: list conversation threads (sidebar)
# ---------------------------------------------------------------------------
@app.get("/api/threads")
async def list_threads():
    return JSONResponse(_read_threads())


@app.post("/api/threads")
async def create_thread():
    thread_id = str(uuid.uuid4())
    await _touch_thread(thread_id)
    return JSONResponse({"thread_id": thread_id})


@app.delete("/api/threads/{thread_id}")
async def delete_thread(thread_id: str):
    async with _threads_lock:
        threads = [t for t in _read_threads() if t["id"] != thread_id]
        _write_threads(threads)
    try:
        os.remove(_ui_history_path(thread_id))
    except FileNotFoundError:
        pass
    return JSONResponse({"ok": True})


# ---------------------------------------------------------------------------
# API: file upload (attachment)
# ---------------------------------------------------------------------------
@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...)):
    safe_name = f"{uuid.uuid4().hex}_{file.filename}"
    dest_path = os.path.join(UPLOADS_DIR, safe_name)
    with open(dest_path, "wb") as f:
        shutil.copyfileobj(file.file, f)
    return JSONResponse({"path": dest_path, "filename": file.filename})


# ---------------------------------------------------------------------------
# HELPERS: turn LangGraph's saved message state into a UI-friendly transcript
# ---------------------------------------------------------------------------
def _stringify(value) -> str:
    try:
        if isinstance(value, (dict, list)):
            return json.dumps(value, ensure_ascii=False, default=str)[:4000]
        return str(value)[:4000]
    except Exception:
        return str(value)[:4000]


def _extract_text(content) -> str:
    """
    Normalizes a LangChain message's .content down to just the
    human-readable answer text.

    Some models (Gemini/Gemma included) return .content as a LIST mixing
    plain strings with structured blocks like {"type": "text", "text": ...}
    and {"type": "thinking", "thinking": ...}. Blindly JSON-dumping that
    list (what _stringify does) leaked the model's internal "thinking"
    trace straight into the chat bubble as raw JSON. This picks out only
    the actual answer text and drops reasoning/other non-text blocks.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                block_type = item.get("type")
                if block_type in ("thinking", "reasoning", "redacted_thinking"):
                    continue
                if block_type == "text" or "text" in item:
                    parts.append(item.get("text", ""))
        return "".join(parts)
    return _stringify(content)


def _agent_from_tool_name(tool_name: str) -> str | None:
    if tool_name and tool_name.startswith("transfer_to_"):
        candidate = tool_name[len("transfer_to_"):]
        if candidate in SUB_AGENT_NAMES:
            return candidate
    return None


def _extract_final_answer(messages) -> str:
    """
    Reliably pulls the SUPERVISOR's own final answer text straight out of
    the graph's saved state, by walking backward from the end until either
    the most recent HumanMessage or a qualifying AIMessage (one with no
    pending tool calls) is found.

    Messages authored by a sub-agent (identified via `.name`, which
    langgraph_supervisor sets in output_mode="full_history") are skipped
    here on purpose — those are surfaced separately as "report" steps (see
    _messages_to_turns) instead of silently overwriting the supervisor's
    own wrap-up. If the supervisor never produces its own wrap-up message,
    the most recent sub-agent answer is used as a fallback so the user
    still sees something instead of nothing.
    """
    fallback = ""
    for msg in reversed(messages):
        if isinstance(msg, HumanMessage):
            break
        if isinstance(msg, AIMessage):
            tool_calls = getattr(msg, "tool_calls", None) or []
            if tool_calls or not msg.content:
                continue
            content = _extract_text(msg.content)
            if not content.strip():
                continue
            author = getattr(msg, "name", None)
            if author and author in SUB_AGENT_NAMES:
                if not fallback:
                    fallback = content
                continue
            return content
    return fallback


def _messages_to_turns(messages):
    """
    Walk a flattened LangGraph message history (as produced by
    langgraph_supervisor with output_mode='full_history') and rebuild
    Manus-style turns: {role: user, text} and
    {role: assistant, steps: [...], text: final_answer}.
    """
    turns = []
    current = None
    pending_tool_calls = {}  # tool_call_id -> step dict

    def _new_assistant_turn():
        return {"role": "assistant", "steps": [], "text": ""}

    for msg in messages:
        if isinstance(msg, HumanMessage):
            turns.append({"role": "user", "text": _extract_text(msg.content)})
            current = _new_assistant_turn()
            turns.append(current)

        elif isinstance(msg, AIMessage):
            if current is None:
                current = _new_assistant_turn()
                turns.append(current)

            tool_calls = getattr(msg, "tool_calls", None) or []
            if tool_calls:
                for tc in tool_calls:
                    tool_name = tc.get("name")
                    agent_name = _agent_from_tool_name(tool_name)
                    if agent_name:
                        step = {"type": "agent_start", "agent": agent_name}
                    else:
                        step = {
                            "type": "tool",
                            "tool": tool_name,
                            "input": _stringify(tc.get("args")),
                            "output": None,
                        }
                    current["steps"].append(step)
                    pending_tool_calls[tc.get("id")] = step
            elif msg.content:
                text = _extract_text(msg.content)
                if text.strip():
                    author = getattr(msg, "name", None)
                    if author and author in SUB_AGENT_NAMES:
                        # This is a sub-agent's own final answer, not the
                        # supervisor's. Surface it as its own visible
                        # "report" step instead of silently overwriting
                        # current["text"] — otherwise the sub-agent's work
                        # was invisible unless the user asked again.
                        current["steps"].append({
                            "type": "report",
                            "agent": author,
                            "output": text,
                        })
                    else:
                        current["text"] = text

        elif isinstance(msg, ToolMessage):
            step = pending_tool_calls.get(msg.tool_call_id)
            if step is not None and step.get("type") == "tool":
                step["output"] = _stringify(msg.content)

    return turns


# ---------------------------------------------------------------------------
# API: load full history for a thread (used on page refresh)
# ---------------------------------------------------------------------------
@app.get("/api/history")
async def history(thread_id: str):
    config = {"configurable": {"thread_id": thread_id}}
    saved_turns = _read_ui_history(thread_id)
    try:
        state = await main_assistant_agent.aget_state(config)
    except Exception:
        return JSONResponse({"turns": saved_turns})
    if not state or not state.values:
        return JSONResponse({"turns": saved_turns})

    messages = state.values.get("messages", [])
    graph_turns = _messages_to_turns(messages)
    # The graph is authoritative when it contains a completed assistant answer.
    # Otherwise return the filesystem transcript, which survives refreshes and
    # checkpointer/provider restore delays.
    has_answer = any(t.get("role") == "assistant" and str(t.get("text", "")).strip() for t in graph_turns)
    turns = graph_turns if has_answer else saved_turns
    if turns:
        _write_ui_history(thread_id, turns)
    return JSONResponse({"turns": turns})


# ---------------------------------------------------------------------------
# API: streaming chat endpoint (NDJSON stream of Manus-style events)
# ---------------------------------------------------------------------------
def _sse(obj: dict) -> str:
    return json.dumps(obj, ensure_ascii=False) + "\n"


def _owning_agent(ns: str, node: str | None) -> str | None:
    """
    Figures out which agent (the main supervisor, or a specific sub-agent)
    an astream_events event actually belongs to.

    Sub-agents built with create_agent() reuse the SAME internal node names
    ("agent" for the model call, "tools" for the tool-call node) as the
    top-level supervisor graph — so `langgraph_node` alone can't tell them
    apart. LangGraph's checkpoint namespace encodes the nesting instead,
    e.g. "git_hub_agent:<run-id>|agent:<run-id-2>" for a call happening
    *inside* the git_hub_agent sub-graph, versus just "agent:<run-id>" for
    the same node name running directly in the top-level graph.
    """
    if not ns:
        return node
    first_segment = ns.split("|")[0]
    return first_segment.split(":")[0] or node


@app.post("/api/chat")
async def chat(
    thread_id: str = Form(...),
    text: str = Form(""),
    attachment_path: str | None = Form(None),
):
    graph = main_assistant_agent
    config = {"configurable": {"thread_id": thread_id}}

    user_text = text or ""
    if attachment_path:
        user_text = f"{user_text}\n\n[সংযুক্ত ফাইল: {attachment_path}]"

    await _touch_thread(thread_id, title=(text or "নতুন কথোপকথন")[:60])
    # Keep a small UI-oriented transcript independently from LangGraph. This
    # prevents a refresh from losing the visible assistant answer when a graph
    # checkpointer is temporarily unavailable or still restoring state.
    _append_ui_turn(thread_id, {"role": "user", "text": text or ""})
    _append_ui_turn(thread_id, {"role": "assistant", "steps": [], "text": ""})

    inputs = {"messages": [HumanMessage(content=user_text)]}

    async def event_stream():
        streamed_text = ""
        queue: asyncio.Queue = asyncio.Queue()
        _DONE = object()

        async def producer():
            # Runs the real graph execution completely independently of the
            # heartbeat loop below. This matters: asyncio.wait_for(coro,
            # timeout) CANCELS `coro` the instant it times out. The old code
            # called asyncio.wait_for() directly on the astream_events
            # iterator's __anext__() — so every time a slow step (a GitHub
            # tool call, a rate-limit retry, etc.) took longer than the 15s
            # heartbeat window, the timeout didn't just skip a beat, it
            # CANCELLED the in-flight graph run outright, killing it silently
            # partway through with no error and no final answer. Running the
            # real work here, in its own task, decouples "how long the graph
            # takes" from "how often we need to send a keep-alive byte".
            try:
                async for event in graph.astream_events(inputs, config=config, version="v2"):
                    await queue.put(("event", event))
            except Exception as exc:  # noqa: BLE001
                await queue.put(("error", exc))
            finally:
                await queue.put(("stop", None))

        producer_task = asyncio.create_task(producer())

        try:
            while True:
                try:
                    # Only queue.get() is subject to the timeout here — a
                    # timeout just means "nothing to report yet", and does
                    # NOT touch producer_task, which keeps running untouched.
                    kind, payload = await asyncio.wait_for(queue.get(), timeout=15)
                except asyncio.TimeoutError:
                    yield _sse({"type": "heartbeat"})
                    continue

                if kind == "stop":
                    break
                if kind == "error":
                    raise payload

                event = payload
                kind = event.get("event")
                metadata = event.get("metadata") or {}
                node = metadata.get("langgraph_node")
                name = event.get("name")
                ns = metadata.get("langgraph_checkpoint_ns", "") or ""
                owning_agent = _owning_agent(ns, node)
                # No "|" in the namespace means this event is happening
                # directly in the top-level graph (the main supervisor's
                # own reasoning/answer), not inside a nested sub-agent.
                is_top_level = "|" not in ns

                if kind == "on_chain_start" and name in SUB_AGENT_NAMES and node == name:
                    yield _sse({"type": "agent_start", "agent": name})

                elif kind == "on_tool_start":
                    yield _sse({
                        "type": "tool_start",
                        "agent": owning_agent,
                        "tool": name,
                        "input": _stringify((event.get("data") or {}).get("input")),
                    })

                elif kind == "on_tool_end":
                    output = (event.get("data") or {}).get("output")
                    yield _sse({
                        "type": "tool_end",
                        "agent": owning_agent,
                        "tool": name,
                        "output": _stringify(output),
                    })

                elif kind == "on_chat_model_stream" and is_top_level:
                    chunk = (event.get("data") or {}).get("chunk")
                    text_piece = getattr(chunk, "content", "") if chunk else ""
                    if isinstance(text_piece, list):
                        text_piece = "".join(
                            part.get("text", "") if isinstance(part, dict) else str(part)
                            for part in text_piece
                        )
                    if text_piece:
                        streamed_text += text_piece
                        yield _sse({"type": "token", "text": text_piece})

            # Guaranteed final answer: don't rely solely on having
            # correctly matched the right live token-stream event above
            # (that filtering has proven fragile across LangGraph/provider
            # versions) — read the real saved state instead, the same
            # reliable source /api/history uses, and send the complete
            # text as one event before signalling done.
            final_text = streamed_text
            final_turn = {"role": "assistant", "steps": [], "text": final_text}
            try:
                final_state = await graph.aget_state(config)
                state_messages = (final_state.values or {}).get("messages", []) if final_state else []
                graph_turns = _messages_to_turns(state_messages)
                latest_assistant = next((t for t in reversed(graph_turns) if t.get("role") == "assistant"), None)
                if latest_assistant:
                    final_turn = latest_assistant
                    # Surface each sub-agent's own final answer as a visible
                    # "report" step — without this, delegated work only
                    # showed up if the user asked again in a follow-up turn.
                    for step in final_turn.get("steps", []):
                        if step.get("type") == "report":
                            yield _sse({
                                "type": "sub_agent_report",
                                "agent": step.get("agent"),
                                "text": step.get("output", ""),
                            })
                final_text = _extract_final_answer(state_messages) or final_turn.get("text") or streamed_text
                final_turn["text"] = final_text
                if final_text:
                    yield _sse({"type": "final_answer", "text": final_text})
            except Exception:
                logger.error("failed to read final state:\n%s", traceback.format_exc())
            _replace_last_assistant_turn(thread_id, final_turn)
            yield _sse({"type": "done"})
        except Exception as exc:  # noqa: BLE001
            logger.error("chat stream failed:\n%s", traceback.format_exc())
            error_text = f"একটি সমস্যা হয়েছে: {exc}"
            _replace_last_assistant_turn(thread_id, {"role": "assistant", "steps": [], "text": error_text})
            yield _sse({"type": "error", "message": str(exc)})
        finally:
            # Guard against leaking the background task if the client
            # disconnects, an error is raised early, etc.
            if not producer_task.done():
                producer_task.cancel()

    return StreamingResponse(
        event_stream(),
        media_type="application/x-ndjson",
        headers={
            # Ask any intermediate reverse proxy (HF Spaces included) not
            # to buffer this response — buffering a streaming response
            # can look identical to a hang from the client's side.
            "X-Accel-Buffering": "no",
            "Cache-Control": "no-cache",
        },
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=7860)
